name: Rust project CI

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            bin: unjosefizer
            name: UnJosefizer-Linux-x86_64-musl.tar.gz
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: unjosefizer.exe
            name: UnJosefizer-Windows-x86_64.zip
            command: build

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: unjosefizer
            name: UnJosefizer-Darwin-x86_64.tar.gz
            command: build

    runs-on:  ${{ matrix.platform.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal
    - name: Cache cargo & target directories
      uses: Swatinem/rust-cache@v2
    - name: Build
      uses: houseabsolute/actions-rust-cross@v0.0.12
      with:
        command: ${{ matrix.platform.command }}
        target: ${{ matrix.platform.target }}
        args: "--locked --release"
        strip: true

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: UnJosefizer-${{ matrix.platform.os_name }}
        path: ./target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}


              
