name: Rust project CI

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - name: Cache cargo & target directories
      uses: Swatinem/rust-cache@v2
    - name: Build
      uses: houseabsolute/actions-rust-cross@v0.0.12
      with:
        command: build
        target: x86_64-pc-windows-msvc
        args: "--locked --release"
        strip: true

    - name: Upload artifacts Win
      uses: actions/upload-artifact@v4
      with:
        name: win-app
        path: ./target/x86_64-pc-windows-msvc/release/unjosefizer.exe


              
